### ISSUE TITLE
[Suggestion] Utilisation de flake8 et eslint

### ISSUE THREAD

**Issue by Melissendra** [zhaoyidai/TP-Angular-Python#3]
Pour le respect de la PEP8 et des bonnes pratique javascript, il existe des outils: flake8 et eslint notamment.
Pouvez-vous essayer de les mettre en place, svp? 

Voici quelques lien pour vous aidez:
[Flake8](https://flake8.pycqa.org/en/latest/)
[angular-eslint](https://github.com/angular-eslint/angular-eslint)

**Comment by zhaoyidai** [comment]
Mis en place flake8 dans mon IDE(PyCharm) et code amélioré en respectant PEP8.

Mis en place eslint.
