### ISSUE TITLE
[Amélioration] Dynamisation méthode editIntervention

### ISSUE THREAD

**Issue by Melissendra** [zhaoyidai/TP-Angular-Python#4]
Actuellement votre méthode editIntervention liste tous les champs qu'il est possible de corriger. Ici c'est pas trop génant car il n'y a pas beaucoup de champs mais dans l'usage réel d'une application il arrive régulièrement qu'il y en ai une multitude. 
Comment feriez vous pour dynamiser cette fonction et la rendre plus facilement maintenable?

**Comment by zhaoyidai** [comment]
Merci pour votre feedback. J'ai mis à jour la méthode `editIntervention` et `addIntervention` pour utiliser un dictionnaire (ou un objet) au lieu de lister tous les champs individuellement.
